project:
  type: website
  render:
    - "*qmd"
    - "*md"
    - "content/*"

website:
  title: "LingMethodsHub"
  site-url: "https://lingmethodshub.github.io"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: content/index.qmd
        text: "Tutorials"
      - about.qmd
      - href: content/contributing/index.md
        text: Contributing
      - href: people/index.qmd
        text: People
    right:
      - href: https://github.com/LingMethodsHub/LingMethodsHub.github.io
        icon: "github"
    search: true        
  sidebar:
    - title: "Home"
      logo: assets/logo.svg
      contents:
        - index.qmd
    - title: "Tutorials"
      collapse-level: 1
      logo: assets/logo.svg
      href: content/index.qmd
      contents:
        - content/index.qmd
        - section: "R"
          href: "content/R/index.md"
          contents:
            - section: "Doing LVC with R"
              href: "content/R/lvc_r/index.qmd"
              contents:
                - href: "content/R/lvc_r/010_lvcr.qmd"
                - href: "content/R/lvc_r/020_lvcr.qmd"
                - href: "content/R/lvc_r/030_lvcr.qmd"
                - href: "content/R/lvc_r/040_lvcr.qmd"                
                - href: "content/R/lvc_r/050_lvcr.qmd"                
                - href: "content/R/lvc_r/060_lvcr.qmd"                
                - href: "content/R/lvc_r/070_lvcr.qmd"                
                - href: "content/R/lvc_r/080_lvcr.qmd"
            - text: "---"
        - text: "---"
        - section: Python
          href: "content/python/index.md"
        - text: "---"
        - section: Praat
          href: "content/praat/index.md"        
        - text: "---"
        - section: Tools
          href: "content/tools/index.md"
          contents:
            - href: content/tools/mfa/mfa-tutorial/index.Rmd
        - text: "---"
        - section: Command Line Interfaces
          href: content/cli/index.md
          contents:
            - href: content/cli/keyboarding/index.qmd
              text: Keyboarding
        - text: "---"
        - section: Windows
          href: content/windows/index.md
          contents:
            - section: Windows Subsystem for Linux
              href: content/windows/wsl/index.md
              contents: 
                - href: content/windows/wsl/00_installing_wsl.md
                  text: Installation
            - text: "---"
        - text: "---"
    - title: "Contributing" 
      href: content/contributing/index.md
      logo: assets/logo.svg
      style: "floating"
      contents: 
        - content/contributing/index.md
        - href: content/contributing/00_requirements.qmd
          text: "Requirements"
        - href: content/contributing/01_recommendations.qmd
          text: "Recommendations"
        - href: content/contributing/02_process.qmd
          text: "Process"
        - href: content/contributing/03_workflow.qmd
          text: "Workflow"
        - text: "---"          
        - section: Template
          contents:
            - href: content/contributing/template/index.qmd
              text: "template index"
            - href: content/contributing/template/00_rmarkdown_template.Rmd
              text: "template rmarkdown"
            - href: content/contributing/template/01_qmd_template.qmd
              text: "template qmd"
            - href: content/contributing/template/02_jupyter.ipynb 
              text: "template jupyter"
    - text: "---"              
    - title: "About" 
      href: about.qmd
      style: "floating"
    - title: "People"
      href: people/index.qmd
      logo: assets/logo.svg
      style: "floating"
      contents: 
        - people/index.qmd   
  page-navigation: true
  reader-mode: true      
  cookie-consent:
    type: express
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: never
  google-analytics: G-ES98D09K0F

format:
  html:
    theme: minty
    include-in-header: google_font.html
    mainfont: "'Atkinson Hyperlegible', sans-serif"
    css: styles.css
    toc: true
    smooth-scroll: true
    code-overflow: wrap

citation:
  collection-title: "Linguistics Methods Hub"
output-format: all
prefer-html: true

execute:
  freeze: auto


