project:
  type: website
  render:
    - "*qmd"
    - "*md"
    - "content/*"

website:
  title: "LingMethodsHub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: content/index.qmd
        text: "Tutorials"
      - about.qmd
      - href: content/contributing/index.md
        text: Contributing
      - href: people/index.qmd
        text: People
    right:
      - href: https://github.com/LingMethodsHub/LingMethodsHub.github.io
        icon: "github"
    search: true        
  sidebar:
    - title: "Home"
      logo: assets/logo.svg
      contents:
        - index.qmd
    - title: "Tutorials"
      collapse-level: 1
      logo: assets/logo.svg
      href: content/index.qmd
      contents:
        - content/index.qmd
        - section: "R"
          contents:
            #- content/R/index.md
            - section: Doing LVC in R
              href: content/R/lvc_r/index.md
              contents:
                - href: "content/R/lvc_r/Getting Started.qmd"
                  text: Getting Started
        - section: Python
        - section: Praat
        - section: Command Line Interfaces
          href: content/cli/index.md
          contents:
            - href: content/cli/keyboarding/index.qmd
              text: Keyboarding
        - section: Windows
          href: content/windows/index.md
          contents:
            - section: Windows Subsystem for Linux
              href: content/windows/wsl/index.md
              contents: 
                - href: content/windows/wsl/00_installing_wsl.md
                  text: Installation
    - title: "Contributing" 
      href: content/contributing/index.md
      logo: assets/logo.svg
      style: "floating"
      contents: 
        - content/contributing/index.md
        - href: content/contributing/00_requirements.qmd
          text: "Requirements"
        - href: content/contributing/01_recommendations.qmd
          text: "Recommendations"
        - href: content/contributing/01_process.qmd
          text: "Process"
    - title: "About" 
      href: about.qmd
      style: "floating"
    - title: "People"
      href: people/index.qmd
      logo: assets/logo.svg
      style: "floating"
      contents: 
        - people/index.qmd   
  page-navigation: true
  reader-mode: true      
  cookie-consent:
    type: express

  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: never
  google-analytics: G-ES98D09K0F



format:
  html:
    theme: minty
    include-in-header: google_font.html
    mainfont: "'Atkinson Hyperlegible', sans-serif"
    css: styles.css
    toc: true

output-format: all

execute:
  freeze: auto


