project:
  type: website
  render:
    - "*qmd"
    - "*md"
    - "content/*"
    - "content/cli/keyboarding/_index.md"
    - "!content/cli/keyboarding/_index.qmd"
    - "!oldsite/"

website:
  title: "LingMethodsHub"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://github.com/LingMethodsHub/LingMethodsHub.github.io
        icon: "github"
    search: true        
  sidebar:
    logo: assets/logo.svg
    style: "floating"
    contents:
      - section: "R"
        contents:
          - content/R/index.md
      - section: "Python"
      - section: "Command Line Interfaces"
      - section: Windows
        contents:
          - section: "Windows Subsystem for Linux"
            contents: 
              - content/windows/wsl/00_installing_wsl.md
  page-navigation: true
  reader-mode: true      
  cookie-consent: true    
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: never


format:
  html:
    theme: minty
    css: styles.css
    toc: true

execute:
  freeze: auto


