---
title: "About"
about:
  template: jolla
  image: "../assets/logo.svg"
  image-shape: rectangle
  links:
    - icon: github
      text: Github Organization
      href: https://github.com/LingMethodsHub
    - icon: github
      text: Ask to Contribute
      href: https://github.com/LingMethodsHub/LingMethodsHub.github.io/issues
editor: 
  markdown: 
    wrap: 72
---

::: {style="text-align: left"}
Many of us who teach Linguistics, especially some technical or
computational aspects, generate a *lot* of content in the form of
handouts, webpages, tutorials, etc. Most of this content is scattered
across our various learning management systems, personal websites,
github repositories, public dropbox links, or just in our local file
systems. But when asked, we're often happy to share our materials with
student or instructor colleagues.

The goal of Linguistics Methods Hub is to provide one space for us to
contribute our materials as a form of Open Scholarship. Materials you
contribute to the Linguistics Methods Hub will be

-   properly attributed
-   minted with a DOI from zenodo.

If you would like to contribute, please see the [materials on
contributing](content/contributing/index.md), and if you would like to
get involved in the site organization and maintenance, contact [one of
the maintainers](people/index.qmd).
:::

------------------------------------------------------------------------

::: text-secondary
The idea for Linguistics Methods Hub came about during conversations at
[Methods XVII](https://methodsxvii.uni-mainz.de/).
:::
